/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleSkeleton: typeof import('./src/components/HomeArticle/components/article-skeleton.vue')['default']
    BlogFooter: typeof import('./src/components/Layout/footer/blog-footer.vue')['default']
    BlogHeader: typeof import('./src/components/Layout/header/blog-header.vue')['default']
    BlogMain: typeof import('./src/components/Layout/main/blog-main.vue')['default']
    BlogSearch: typeof import('./src/components/Search/blog-search.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GsapCount: typeof import('./src/components/GsapCount/index.vue')['default']
    HomeArticleList: typeof import('./src/components/HomeArticle/home-article-list.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Login: typeof import('./src/components/Layout/header/login/index.vue')['default']
    MobileTopSkeleton: typeof import('./src/components/RightSide/components/skeleton/mobile-top-skeleton.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    RightSide: typeof import('./src/components/RightSide/right-side.vue')['default']
    RightSideItem: typeof import('./src/components/RightSide/components/item/right-side-item.vue')['default']
    RightSideSkeletonItem: typeof import('./src/components/RightSide/components/skeleton/right-side-skeleton-item.vue')['default']
    RightSideTop: typeof import('./src/components/RightSide/components/item/right-side-top.vue')['default']
    RightSideTopSkeleton: typeof import('./src/components/RightSide/components/skeleton/right-side-top-skeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonItem: typeof import('./src/components/SkeletonItem/skeleton-item.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine/time-line.vue')['default']
    Tooltip: typeof import('./src/components/ToolTip/tooltip.vue')['default']
  }
}
